### ISSUE TITLE
OakVar do not uninstalling completely 

### ISSUE THREAD

**Issue by Alex-Karmazin** [rkimoakbioinformatics/oakvar#29]
**Describe the bug**
Command "pip uninstall oakvar" do not remove oakvar root folder and UserData/User/.oakvar folders. It causes that in case of problems you can't be sure that you could do fresh installation without interference with previous version.

**Desktop (please complete the following information):**
 - OS:Windows 10
 - OakVar Version e.g. v2.5.x
 - Browser (if used) chrome

**Comment by antonkulaga** [comment]
I disagree with @Alex-Karmazin , it is not what pip should do, for such stuff things like conda/micromamba are used. Also, deleting oakvar data folder will cause troubles when you want to update without downloading whole dbsnp and other stuff. I think there just be a command at oakvar to delete/move it or check if it is not broken

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin The behavior is intentional and the main reasons are what Anton described. `ov system setup --clean` provides clean installation. It will reset the system and user configuration files. `--clean` still do not delete `modules`, `jobs`, `logs`, and `conf` folders. The system conf file is already reset with `--clean` and the other files in `conf` are just content. What are in `jobs` and `logs` are also just content. `modules` have downloaded modules, and I believe that it's best to let users manually delete this folder if they really want, because this folder can take a lot of time to recreate and also, there are users who keep this folder in a USB drive or something and move it around, while installing and deleting oakvar.

**Comment by Alex-Karmazin** [comment]
Thank you. Please note this in documentation because it is not obvious and some times could be very helpful.

**Comment by rkimoakbioinformatics** [comment]
@Alex-Karmazin The docs have been updated with the clean install information.
